import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import { CosmosProvider, QueryProvider } from '~/providers';
import '~/styles/globals.css';

import { Toaster } from '~/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <QueryProvider>
        <CosmosProvider>
          <body className={`font-sans ${GeistSans.variable}`}>
            {children}
            <Toaster />
          </body>
        </CosmosProvider>
      </QueryProvider>
    </html>
  );
};

export default RootLayout;
